### ISSUE TITLE
error in combination with spree

### ISSUE THREAD

**Issue by tomg65** [AlchemyCMS/alchemy-pg_search#1]
Hi,
I tried to use this gem in an alchemy app with spree included

```
gem 'alchemy_cms', github: 'AlchemyCMS/alchemy_cms', tag: 'v3.1.0.rc1'
gem 'alchemy-pg_search', github: 'AlchemyCMS/alchemy-pg_search'

gem 'spree', github: 'spree/spree', branch: '2-4-stable'
gem 'spree_i18n', github: 'spree/spree_i18n', branch: '2-4-stable'
gem 'alchemy_spree', github: 'AlchemyCMS/alchemy_spree'

```

If the search form is submitted the following error occurs:

```
NoMethodError (undefined method `page' for #<Ransack::Search:0x007fde6daa4c38>):
  ransack (1.4.1) lib/ransack/search.rb:101:in `method_missing'
 /lib/alchemy/pg_search/controller_methods.rb:42:in `perform_search'
```

I think it's because spree requires the ransack gem? Ransack uses the `search` method by default.

```
    def perform_search
        if self.class == Alchemy::Admin::PagesController && params[:query].blank?
          params[:query] = 'lorem'
        end
        return if params[:query].blank?
        @search_results = search_results

        #The @search_results is now a Ransack::Search Object
        @search_results = @search_results.page(params[:page]).per(10)
     end

     def search_results
        pages = Page.published.contentpages.with_language(Language.current.id)
        # Since CanCan cannot (oh the irony) merge +accessible_by+ scope with pg_search scopes,
        # we need to fake a page object here
        if can? :show, Alchemy::Page.new(restricted: true, public: true)
          #Here the search method is called
          pages.search(params[:query])
        else
          pages.not_restricted.search(params[:query])
        end
      end


```

Regards Thomas

**Comment by tvdeyen** [comment]
This is a conflict between Spree using `ransack` and the `pg_search` gem. Usually ransack tries to not override a search method if its already available

https://github.com/activerecord-hackery/ransack#ransack-search-method

I just found out the we are defining the `#search` method while defining the `pg_search_scope` in https://github.com/AlchemyCMS/alchemy-pg_search/blob/master/lib/alchemy/pg_search/page_extension.rb#L6

We could change that to `full_text_search` or `pg_search` for instance.

PR anyone?
